# Generated by Django 2.2.4 on 2020-10-17 21:33

from django.db import migrations


def fill_flats_with_new_buildings(apps, schema_editor):
    flats = apps.get_model("property", "Flat")
    for flat in flats.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


def unfill_flats_with_new_buildings(apps, schema_editor):
    flats = apps.get_model("property", "Flat")
    for flat in flats.objects.all():
        flat.new_building = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(
            fill_flats_with_new_buildings, unfill_flats_with_new_buildings
        )
    ]
