# Generated by Django 2.2.4 on 2020-10-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_auto_20201018_0033"),
    ]

    operations = []
