# Generated by Django 2.2.4 on 2020-10-19 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0006_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="likes",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
