# Generated by Django 2.2.4 on 2020-10-19 20:54

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_flat_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="RU"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул",
            ),
        ),
    ]
