# Generated by Django 2.2.4 on 2020-10-19 21:10
import phonenumbers

from django.db import migrations


def fill_pure_numbers_field(apps, schema):
    try:
        Flats = apps.get_model("property", "Flat")
        for flat in Flats.objects.all():
            if not flat.owner_pure_phone:
                num = flat.owners_phonenumber
                pure_num = phonenumbers.parse(f"{num}", "RU")
                if phonenumbers.is_valid_number(pure_num):
                    flat.owner_pure_phone = phonenumbers.format_number(
                        pure_num, phonenumbers.PhoneNumberFormat.INTERNATIONAL
                    )
                    flat.save()

    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_auto_20201019_2354"),
    ]

    operations = [migrations.RunPython(fill_pure_numbers_field)]
