# Generated by Django 2.2.4 on 2020-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_auto_20201020_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                related_name="owners",
                to="property.Flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="ФИО владельца"
            ),
        ),
    ]
